name: CI
on:
  push:
    branches: 
      - main
    paths: 
      - 'src/**'
      - .github/workflows/build.yml
jobs:
  Container-Build:
    runs-on: ubuntu-latest
    container: m365pnp/spfx:1.14.0
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: gulp bundle --ship
  VM-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.0'
      - run: npm i -g gulp@4
      - run: npm install
      - run: gulp bundle --ship
